project_name: slv
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: "-X github.com/shibme/slv/cli/commands.AppName={{.ProjectName}} -X github.com/shibme/slv/cli/commands.Version={{.Version}}"
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: slv
    homepage: "https://github.com/shibme/slv"
    commit_author:
      name: shibme
      email: git@shib.me
    repository:
      owner: shibme
      name: homebrew-tap
      branch: main
      git:
        url: 'git@github.com:shibme/homebrew-tap.git'
        private_key: '{{ .Env.HOMEBREW_SSH_KEY }}'
