name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code - SLV Beta
        uses: actions/checkout@v4
      - name: Checkout Code - SLV
        uses: actions/checkout@v4
        with:
          repository: shibme/slv
          ref: main
          path: slv
          ssh-key: ${{ secrets.SLV_REPO_READ_SSH_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_SSH_KEY: ${{ secrets.HOMEBREW_SSH_KEY }}